version: '2.0'

services:
  registry:
    image: registry:2.6.2
    volumes:
      - ./registry-data:/var/lib/registry
    ports:
      - 5050:5000
    
  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=Registre Docker Privé
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
      