apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: exam
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: backend
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exam
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: oussamazaam/firstimage
          # image: oussamazaam/secondimage:v2
          resources: {}
          ports:
            - containerPort: 5000
              name: back-port
          # env:
          #   - name: CONNECTION_STRING
          #     valueFrom:
          #       secretKeyRef:
          #         name: examplemongodb-admin-myuser
          #         key: connectionString.standardSrv
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket:
                port: 5000
            periodSeconds: 10
            failureThreshold: 3
          